name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
  - cron: '0 0 * * 1'  # At 00:00 on Mondays.
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ferronn/php-pgsql
          tags: |
            ferronn/php-pgsql:latest
            type=raw,value={{date 'DD.MM.YYYY'}}

      - name: Build and push Docker image
        uses: docker/build-push-action@3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
            
